## Numpy Array Operation

### Slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Slicing from index 2 to 8:", arr[2:8])
print("Slicing with step 2:", arr[2:8:2])
print("Negative indexing:", arr[-8:-2])

Slicing from index 2 to 8: [3 4 5 6 7 8]
Slicing with step 2: [3 5 7]
Negative indexing: [3 4 5 6 7 8]


In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])  # Element at 2nd row, 3rd column -> indexing of element 0, 1, 2
print("Entire row:", arr_2d[1]) # Entire 2nd row (indexing based on 0)
print("Entire column:", arr_2d[:, 2]) # Entire 3rd column (indexing based on 0)


Specific element 6
Entire row: [4 5 6]
Entire column: [3 6 9]


### Sorting

In [4]:
unsorted = np.array([3,1,4,2,5])
print("sorted array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2D array by columns:\n", np.sort(arr_2d_unsorted, axis=0)) #mostly used
print("Sorted 2D array by rows:\n", np.sort(arr_2d_unsorted, axis=1))

sorted array: [1 2 3 4 5]
Sorted 2D array by columns:
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by rows:
 [[1 3]
 [1 2]
 [2 3]]


### Filtering

In [5]:
# IMPORTANT: Expression inside the brackets
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] #Masking
print("Even numbers:", even_number)

Even numbers: [ 2  4  6  8 10]


### Filter with mask

In [6]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [7]:
indices = [0, 2, 4,]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("Numbers greater than 5 using where:", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9], dtype=int64),)
Numbers greater than 5 using where: [ 6  7  8  9 10]


In [8]:
# Conditional array
condition_arr = np.where(numbers > 5, "true", "false")
print("Condition array:", condition_arr)

# under the hood
# if(numbers > 5):
#    print("true")
# else:
#    print("false")

Condition array: ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print("adding array:", arr1 + arr2) #element wise addition - matrix addition
print("subtracting array:", arr2 - arr1) #element wise subtraction
print("Concanating array:", np.concatenate((arr1, arr2))) #merging two arrays

adding array: [5 7 9]
subtracting array: [3 3 3]
Concanating array: [1 2 3 4 5 6]
