# Numpy - (Numerical Python)

In [3]:
import numpy as np

## Creating Arrays from List

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1d Arrays: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d Arrays: ",arr_2d)

1d Arrays:  [1 2 3 4 5]
2d Arrays:  [[1 2 3]
 [4 5 6]]


## List v/s Numpy array

In [ ]:
py_list = [2,3,4] #list multiplication - double the list
print("List Multiplication result:", py_list * 2)

np_arr = np.array([4,5,6]) #element wise multiplication
print("Numpy Array Multiplication result:", np_arr * 2)

List Multiplication result: [2, 3, 4, 2, 3, 4]
Numpy Array Multiplication result: [ 8 10 12]


### Efficency of List and Numpy array

In [9]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Python List Time:", time.time() - start)

start1 = time.time()
np_arr = np.arange(1000000) * 2
print("Numpy Array Time:", time.time() - start1)

Python List Time: 0.0774989128112793
Numpy Array Time: 0.003103971481323242


## Creating array from scratch

In [13]:
zeros = np.zeros((3,4))
print("Zeros array:\n", zeros)

ones = np.ones((2,3))
print("Ones array:\n", ones)

full = np.full((2,2),1) # one dimentional array of 2 elements with all values as 1
print("Full array:\n", full)

random = np.random.random((2,2)) #2x2 array with random values
print("Random array:\n", random)

sequence = np.arange(10,20,2) #start, end, step
print("Sequence array:\n", sequence)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array:
 [[1 1]
 [1 1]]
Random array:
 [[0.11618701 0.64653448]
 [0.12916559 0.80616707]]
Sequence array:
 [10 12 14 16 18]


## Vector, Matrix and Tensor

In [14]:
vector = np.array([1,2,3,4,5])
print("Array:", vector)
print("Shape of array:", vector.shape)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix:\n", matrix)
print("Shape of matrix:", matrix.shape)

tensor = np.array([[1,2],[3,4],[5,6]])
print("Tensor:\n", tensor)
print("Shape of tensor:", tensor.shape)

Array: [1 2 3 4 5]
Shape of array: (5,)
Matrix:
 [[1 2 3]
 [4 5 6]]
Shape of matrix: (2, 3)
Tensor:
 [[1 2]
 [3 4]
 [5 6]]
Shape of tensor: (3, 2)


### Array Properties

In [16]:
new_arr = np.array([[1,2,3], [3,4,5]])
print("Shape:", new_arr.shape)
print("Dimensions:", new_arr.ndim)
print("Data Type:", new_arr.dtype)
print("Size:", new_arr.size)

Shape: (2, 3)
Dimensions: 2
Data Type: int32
Size: 6


## Array Reshaping

In [18]:
arr = np.arange(10)
print("Original array:", arr)

reshaped = arr.reshape(2,5)
print("Reshaped array (2x5:\n", reshaped)

flattened = reshaped.flatten()
print("Flattened array:", flattened)

raveled = reshaped.ravel() #returns view instead of copy
print("Raveled array:", raveled)

transpose = reshaped.T #transpose: rows become columns and vice versa
print("Transposed array:\n", transpose)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reshaped array (2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Flattened array: [0 1 2 3 4 5 6 7 8 9]
Raveled array: [0 1 2 3 4 5 6 7 8 9]
Transposed array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
